#!/bin/bash
#PBS -l select=1:system=polaris
#PBS -l walltime=01:00:00,filesystems=home:grand
#PBS -A TFXcan
#PBS -q debug   
#PBS -N predixcan_cwas_individuals_imputed
#PBS -k doe
#PBS -o /grand/projects/TFXcan/imlab/users/temi/projects/TFXcan/prediXcan/log/predixcan_cwas_individuals_imputed.out
#PBS -e /grand/projects/TFXcan/imlab/users/temi/projects/TFXcan/prediXcan/log/predixcan_cwas_individuals_imputed.err

echo Working directory is $PBS_O_WORKDIR
cd $PBS_O_WORKDIR

# echo Jobid: $PBS_JOBID
# echo Running on host `hostname`
# echo Running on nodes `cat $PBS_NODEFILE`

# NNODES=`wc -l < $PBS_NODEFILE`
# NRANKS=1
# NDEPTH=48
# NTHREADS=2

# #NTOTRANKS=$(( NNODES * NRANKS ))
# NTOTRANKS=$(( NNODES * NRANKS_PER_NODE ))
# echo "NUM_OF_NODES=${NNODES}  TOTAL_NUM_RANKS=${NTOTRANKS}  RANKS_PER_NODE=${NRANKS}  THREADS_PER_RANK=${NTHREADS}"
# echo "PBS_JOBID = " $PBS_JOBID
# printf "Starting to run\n"

source ~/.bashrc
conda activate imlabtools
module load gnu-parallel

temi_dir="/grand/projects/TFXcan/imlab/users/temi"
predixcan_dir="/grand/projects/TFXcan/imlab/users/temi/projects/TFXcan/prediXcan"
joblog="/grand/projects/TFXcan/imlab/users/temi/projects/TFXcan/prediXcan/log/predict_cwas_task.log"
#utility_script=/lus/grand/projects/TFXcan/imlab/users/temi/projects/TFXcan/scripts/prediXcan/predict_utils.sh
db_list="/lus/grand/projects/TFXcan/imlab/users/temi/projects/TFXcan/scripts/prediXcan/db_list.txt"


function predict_cwas_weights () {

    weights_db=${1}
    #vcf_file_pattern=${2} # full path to the vcf file
     # full path to the weights db
    predixcan_dir=${2} # full path to the predixcan dir
    predict_exe=/lus/grand/projects/TFXcan/imlab/users/temi/software/MetaXcan/software/Predict.py
    vcf_file_pattern='/lus/grand/projects/TFXcan/imlab/data/baca_cwas/imputed_vcf_hg38_snps_only/chr*.dose.vcf.gz'

    printf "\nINFO - running ${weights_db}\n"

    m_name=$( echo ${weights_db} | rev | cut -d '_' -f 1 | rev )
    m_name=${m_name%.*}

    printf "\nINFO - running ${m_name}\n"

    # echo weights = $weights_db
    # echo vcf pattern = $vcf_file_pattern
    # echo predixcan dir = $predixcan_dir

    ${predict_exe} \
    --model_db_path ${weights_db} \
    --vcf_genotypes ${vcf_file_pattern} \
    --vcf_mode genotyped \
    --on_the_fly_mapping METADATA "{}_{}_{}_{}_b38" \
    --variant_mapping "${predixcan_dir}/tutorial/data/gtex_v8_eur_filtered_maf0.01_monoallelic_variants.txt.gz" id rsid \
    --prediction_output "${predixcan_dir}/output/cwas_individuals_imputed/${m_name}/baca_cwas_predict.txt" \
    --prediction_summary_output "${predixcan_dir}/output/cwas_individuals_imputed/${m_name}/baca_cwas_summary.txt" \
    --verbosity 9 \
    --throw

    #--text_sample_ids "/lus/grand/projects/TFXcan/imlab/users/temi/projects/TFXcan/TFPred_pipeline/metadata/predixcan_geuvadis_240.txt"

    printf "INFO - finished ${m_name}"
}

export -f predict_cwas_weights

#vcf_file_pattern="/lus/grand/projects/TFXcan/imlab/data/baca_cwas/split_vcf/chr\*_CWAS_SNPs_2023-05-15_phased.vcf.gz"

#mpiexec="mpiexec -n 1 --ppn 1"
parallel --delay 0.2 -j 3 --joblog ${joblog} "predict_cwas_weights {} ${predixcan_dir}" ::: < ${db_list}

printf "\nINFO - Finished with all models."