#!/bin/bash
#PBS -l select=1:system=polaris
#PBS -l walltime=01:00:00,filesystems=home:grand
#PBS -A covid-ct
#PBS -q debug   
#PBS -N compare_vcfs
#PBS -k doe
#PBS -o /lus/grand/projects/TFXcan/imlab/users/temi/projects/TFXcan/logs/compare_vcfs.out
#PBS -e /lus/grand/projects/TFXcan/imlab/users/temi/projects/TFXcan/logs/compare_vcfs.err

echo Working directory is $PBS_O_WORKDIR
cd $PBS_O_WORKDIR

source ~/.bashrc
conda activate /lus/grand/projects/TFXcan/imlab/users/temi/software/conda_envs/compbio-tools
module load gnu-parallel

first_dir=/lus/grand/projects/TFXcan/imlab/users/temi/projects/TFXcan/geuvadis_individuals/vcf_files
second_dir=/lus/grand/projects/TFXcan/imlab/data/baca_cwas/imputed_vcf_hg38
third_dir=/lus/grand/projects/TFXcan/imlab/data/baca_cwas/vcf_chr_only_hg38
output_dir=/lus/grand/projects/TFXcan/imlab/users/temi/projects/TFXcan/misc/compare_vcfs

# seq 1 22 | parallel -j 22 "tabix -p vcf chr{}.dose.vcf.gz"

seq 1 22 | parallel -j 22 "bcftools stats ${first_dir}/chr{}_99_individuals.vcf.gz ${second_dir}/chr{}.dose.vcf.gz > ${output_dir}/summary_chr{}_imputed.stats"
seq 1 22 | parallel -j 22 "bcftools stats ${first_dir}/chr{}_99_individuals.vcf.gz ${third_dir}/chr{}_CWAS_SNPs_2023-05-30_phased.vcf.gz > ${output_dir}/summary_chr{}_unimputed.stats"


# bcftools stats /lus/grand/projects/TFXcan/imlab/users/temi/projects/TFXcan/geuvadis_individuals/vcf_files/chr10_99_individuals.vcf.gz /lus/grand/projects/TFXcan/imlab/data/baca_cwas/split_hg38_vcf/chr10_CWAS_SNPs_2023-05-15_phased.vcf.gz > summary.txt

# bcftools view -v snps /lus/grand/projects/TFXcan/imlab/users/temi/projects/TFXcan/geuvadis_individuals/vcf_files/chr10_99_individuals.vcf.gz | grep -v "^#" | wc -l