#!/bin/bash --login 

#PBS -A covid-ct
#PBS -l walltime=00:40:00
#PBS -N format_files
#PBS -l select=4
#PBS -l filesystems=home:grand
#PBS -q preemptable
#PBS -o /lus/grand/projects/TFXcan/imlab/users/temi/projects/TFXcan/logs/format_files.out
#PBS -e /lus/grand/projects/TFXcan/imlab/users/temi/projects/TFXcan/logs/format_files.err
#PBS -k doe

pbs_workdir=${PBS_O_WORKDIR}/${PBS_JOBNAME}
PBS_O_WORKDIR=${pbs_workdir}
mkdir -p ${PBS_O_WORKDIR}
cd $PBS_O_WORKDIR

NNODES=`cat ${PBS_NODEFILE} | sort -u | wc -l`
NRANKS=1
NDEPTH=48
NTHREADS=2

#NTOTRANKS=$(( NNODES * NRANKS ))
NTOTRANKS=$(( NNODES * NRANKS_PER_NODE ))

echo "NUM_OF_NODES=${NNODES}  TOTAL_NUM_RANKS=${NTOTRANKS}  RANKS_PER_NODE=${NRANKS_PER_NODE}  THREADS_PER_RANK=${NTHREADS}"

source ~/.bashrc
#conda activate compbio-tools
conda activate /lus/grand/projects/TFXcan/imlab/users/temi/software/conda_envs/compbio-tools

# variables
mpiexec="/opt/cray/pe/pals/1.1.7/bin/mpiexec"
vcfs_path=/lus/grand/projects/TFXcan/imlab/data/GEUVADIS/vcf_snps_only
plink_results_folder=/lus/grand/projects/TFXcan/imlab/data/GEUVADIS/plink_geno
formatted_files_folder=/lus/grand/projects/TFXcan/imlab/data/GEUVADIS/formatted_geno
exec_file=/lus/grand/projects/TFXcan/imlab/users/temi/projects/TFXcan/scripts/predictDB_helpers/format_files.sh
mkdir -p ${plink_results_folder}
mkdir -p ${formatted_files_folder}

vcf_list=/lus/grand/projects/TFXcan/imlab/users/temi/projects/TFXcan/scripts/predictDB_helpers/chr_vcfs.txt # created by: printf '%s\n' /lus/grand/projects/TFXcan/imlab/data/GEUVADIS/vcf_snps_only/*.gz > chr_vcfs.txt
#split -n ${NNODES} ${vcf_list} vcf_ --numeric-suffixes=1 --suffix-length=2
x=`wc -l ${vcf_list} | awk '{print $1}'`
y=${NNODES} 
ll=$(( ($x + $y - 1) / $y ))

split --lines="${ll}" --numeric-suffixes=1 --suffix-length=1 "${vcf_list}" "vcf_"

# Increase value of suffix-length if more than 99 jobs
NUM_NODES_PER_MPI=1
split --lines=${NUM_NODES_PER_MPI} --numeric-suffixes=1 --suffix-length=1 $PBS_NODEFILE "local_hostfile."

for suf in `seq 1 ${NNODES}`; do
  #IFS=,$'\n' read -d '' -r -a vcf_arr < "vcf_${suf}"
  (
    echo "${suf}(`cat local_hostfile.${suf}`)-vcf_${suf}"

    ${mpiexec} -n 1 --ppn 1 --hostfile "local_hostfile.${suf}" --depth ${NDEPTH} --cpu-bind depth --env OMP_NUM_THREADS="${NTHREADS}" ${exec_file} "vcf_${suf}" "${plink_results_folder}" ${formatted_files_folder}
  ) & sleep 1
done
wait

printf '\n%s\n' "INFO - merging all files into one"

/home/temi/miniconda3/envs/r-env/bin/Rscript /lus/grand/projects/TFXcan/imlab/users/temi/projects/TFXcan/scripts/manipulate_vcfs/vcfs_utils.R --command "merge_genotype_dosage_and_snp_annot_files" --files_folder ${formatted_files_folder} --output_folder ${formatted_files_folder}

printf '\n%s\n' "Finished preparing all VCF files\n"