

# directories
base_dir: '/lus/grand/projects/covid-ct/imlab'
data_dir: '/lus/grand/projects/covid-ct/imlab/data/cistrome/raw'
project_dir: '/lus/grand/projects/covid-ct/imlab/users/temi/projects/TFXcan/TFPred_pipeline'
dataset: 'cistrome' # change this variable name 
date: null
TF_table: '/lus/grand/projects/covid-ct/imlab/data/cistrome/raw/human_factor_full_QC.txt' 

homer:
  dir: '/lus/grand/projects/covid-ct/imlab/users/temi/software/homer'
