#!/bin/bash
#PBS -l select=1:system=polaris
#PBS -l walltime=01:00:00,filesystems=home:grand
#PBS -A covid-ct
#PBS -q debug   
#PBS -N sort_bedfiles
#PBS -k doe
#PBS -o /grand/projects/TFXcan/imlab/users/temi/projects/TFXcan/logs/sort_bedfiles.out
#PBS -e /grand/projects/TFXcan/imlab/users/temi/projects/TFXcan/logs/sort_bedfiles.err

echo Working directory is $PBS_O_WORKDIR
cd $PBS_O_WORKDIR

source ~/.bashrc
conda activate r-env
module load gnu-parallel

bedfiles=( `find /lus/grand/projects/TFXcan/imlab/data/baca_cwas/liftover_hg38 -not -name 'unmapped_*.bed' -type f` )
bedtools='/home/temi/miniconda3/envs/compbio-tools/bin/bedtools'
sorted_dir=/lus/grand/projects/TFXcan/imlab/data/baca_cwas/sorted_bed_hg38
mkdir -p ${sorted_dir}

# echo ${bedfiles}
# basenames=$( echo ${bedfiles} | rev | cut -d '/' -f 1 | rev | cut -d '.' -f 1 )
# echo ${basenames}

function sortbed (){
    bedfile=${1}
    sorted_dir=${2}
    basename=$( echo ${bedfile} | rev | cut -d '/' -f 1 | rev | cut -d '.' -f 1 )
    #bedtools='/home/temi/miniconda3/envs/compbio-tools/bin/bedtools'
    printf "\nINFO - running ${basename}\n"
    #${bedtools} sort -i ${bedfile} > ${sorted_dir}/${basename}.sorted.bed
    sort -k1,1 -k2,2n ${bedfile} > ${sorted_dir}/${basename}.sorted.bed
    printf "\nINFO - finished ${basename}\n"
}

export -f sortbed

parallel -j 12 --joblog '/lus/grand/projects/TFXcan/imlab/users/temi/projects/TFXcan/logs/sortbed_task.log' "sortbed {} ${sorted_dir}" ::: ${bedfiles[@]}