---
title: "Compare R-TFPred with L-TFPred"
author: "Temi"
date: 'Wed June 28 2023'
format: 
  pdf: 
    toc: true
    number-sections: true
    code-line-numbers: true
---

```{r}
rm(list=ls())
expr_dir <- '/lus/grand/projects/TFXcan/imlab/users/temi/projects/TFXcan/experiments'
```

```{r}
library(devtools)
library(glue)
library(GenomicRanges)
library(reticulate)
library(R.utils)
library(data.table)
library(tidyverse)
library(annotatr)
library(AnnotationHub)
library(biomaRt)
library(hexbin)
library(RColorBrewer)
library(preprocessCore)
library(grid)
library(gridExtra)
```

### After predictions

```{r}
#setwd('/grand/TFXcan/imlab/users/temi/projects/TFXcan/scripts/')
project_dir <- '/lus/grand/projects/TFXcan/imlab/users/temi/projects/TFXcan'
enhancers_dir <- '/lus/grand/projects/TFXcan/imlab/data/enhancers'

# for qqplots:
#devtools::source_gist('https://gist.github.com/TemiPete/250d9922b9516691f83bb1fd999a3ccc')

# for manhattan plots
devtools::source_gist('https://gist.github.com/TemiPete/250d9922b9516691f83bb1fd999a3ccc')
devtools::source_gist('https://gist.github.com/hakyim/38431b74c6c0bf90c12f')
devtools::source_gist('https://gist.github.com/hakyim/5d2251ea1a86009499e4ffdf47fe2735')
```

### Check that CWAS loci exist

```{r}
cwas_loci <- 
```
